### ISSUE TITLE
not working on Html files.

### ISSUE THREAD

**Issue by ctf0** [JuDelCo/Highlight-Changes#2]
its working fine on other ext ,here is the console log

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 271, in on_modified
    callback.on_modified(v)
  File "Hightlight Changes in /Users/Novo/Library/Application Support/Sublime Text 3/Installed Packages/Highlight-Changes.sublime-package", line 16, in on_modified
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11252: ordinal not in range(128)
```

**Comment by ctf0** [comment]
its related to another plugin ,all good now.
